begin;
select plan(17);
select has_table('public', 'fiscal_profiles', 'fiscal profiles exist');
select has_table('public', 'fiscal_treatments', 'fiscal treatments exist');
select has_table('public', 'fiscal_documents', 'fiscal documents exist');
select has_table('public', 'fiscal_attempts', 'fiscal attempts exist');
select has_column('public', 'fiscal_profiles', 'version', 'profiles are versioned');
select has_column('public', 'fiscal_treatments', 'source_kind', 'treatments identify source');
select has_column('public', 'fiscal_documents', 'amount_cents', 'documents use integer cents');
select has_column('public', 'fiscal_documents', 'idempotency_key', 'documents are idempotent');
select has_column('public', 'fiscal_documents', 'treatment_version', 'documents snapshot treatment');
select has_column('public', 'fiscal_documents', 'xml_path', 'xml uses private artifact reference');
select has_column('public', 'fiscal_documents', 'pdf_path', 'pdf uses private artifact reference');
select ok((select count(*) from public.fiscal_treatments) = 5, 'all fiscal source kinds are explicit');
select ok((select count(*) from pg_policies where schemaname = 'public' and tablename = 'fiscal_documents') = 1, 'documents have one restricted policy');
select ok((select relrowsecurity from pg_class where oid = 'public.fiscal_documents'::regclass), 'documents enable RLS');
select ok((select relforcerowsecurity from pg_class where oid = 'public.fiscal_documents'::regclass), 'documents force RLS');
select ok((select count(*) = 1 from pg_trigger where tgrelid = 'public.fiscal_documents'::regclass and tgname = 'fiscal_documents_guard_before_update'), 'issued documents have update guard');
select * from finish();
rollback;
