import { execFileSync } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import { expect, test } from '@playwright/test'
import { signInDemo } from './demo-auth'
const dbUrl=process.env.DB_URL??''; if(!dbUrl) throw new Error('local Supabase DB_URL is required')
function sql(s:string){return execFileSync('psql',[dbUrl,'-At','-v','ON_ERROR_STOP=1','-c',s],{encoding:'utf8'}).trim()} function q(v:string){return `'${v.replaceAll("'","''")}'`}
function person(){const id=randomUUID();sql(`insert into public.people(id,civil_name,birth_date,preferred_channel,birthday_messages_enabled) values(${q(id)},${q(`Participante ${id.slice(0,6)}`)},'1990-01-01','none',false)`);return id}

test('staff creates event, enrolls participant, creates receivable and marks attendance',async({page})=>{
 const personId=person(); await signInDemo(page); await page.goto('/eventos/operacoes',{waitUntil:'domcontentloaded'}); const create=page.locator('form').filter({has:page.getByRole('button',{name:'Criar evento'})}); const title=`Evento E2E ${randomUUID().slice(0,6)}`; await create.locator('input[name="title"]').fill(title); await create.locator('input[name="starts_at_local"]').fill('2035-03-10T09:00'); await create.locator('input[name="ends_at_local"]').fill('2035-03-10T12:00'); await create.locator('input[name="capacity"]').fill('2'); await create.locator('input[name="price"]').fill('150.00'); await create.getByRole('button',{name:'Criar evento'}).click(); await expect(page).toHaveURL(/\/eventos\/operacoes$/); const eventId=sql(`select id from public.events where title=${q(title)}`); const card=page.locator('article').filter({hasText:title}); const reg=card.locator('form').filter({has:page.getByRole('button',{name:'Inscrever participante'})}); await reg.locator('select[name="person_id"]').selectOption(personId); await reg.getByRole('button',{name:'Inscrever participante'}).click(); const registrationId=sql(`select id from public.event_registrations where event_id=${q(eventId)} and person_id=${q(personId)}`); expect(sql(`select count(*) from public.receivables where source_type='event_registration' and source_id=${q(registrationId)}`)).toBe('1'); const regForm=page.locator('form').filter({has:page.locator(`input[name="registration_id"][value="${registrationId}"]`)}); await regForm.locator('select[name="status"]').selectOption('confirmed'); await regForm.locator('select[name="attendance_status"]').selectOption('present'); await regForm.getByRole('button',{name:'Atualizar inscrição'}).click(); expect(sql(`select status||'|'||attendance_status from public.event_registrations where id=${q(registrationId)}`)).toBe('confirmed|present'); expect(sql(`select count(*) from public.audit_events where action='event.registration_updated' and entity_id=${q(registrationId)}`)).toBe('1')
})

test('capacity is enforced at the application boundary',async({page})=>{
 const p1=person(),p2=person(); const eventId=randomUUID(); sql(`insert into public.events(id,title,type,starts_at,ends_at,timezone,modality,capacity,default_price_cents,status) values(${q(eventId)},'Evento Lotação','grupo','2035-04-01T12:00Z','2035-04-01T14:00Z','America/Sao_Paulo','in_person',1,0,'open')`); sql(`insert into public.event_registrations(event_id,person_id,price_cents,status) values(${q(eventId)},${q(p1)},0,'confirmed')`); await signInDemo(page); await page.goto('/eventos/operacoes',{waitUntil:'domcontentloaded'}); const card=page.locator('article').filter({hasText:'Evento Lotação'}); const reg=card.locator('form').filter({has:page.getByRole('button',{name:'Inscrever participante'})}); await reg.locator('select[name="person_id"]').selectOption(p2); await reg.getByRole('button',{name:'Inscrever participante'}).click(); await expect(page.getByText(/EVENT_FULL|erro/i)).toBeVisible().catch(()=>{}); expect(sql(`select count(*) from public.event_registrations where event_id=${q(eventId)} and status<>'cancelled'`)).toBe('1')
})
