import { execFileSync } from 'node:child_process'
import { randomUUID } from 'node:crypto'
import { expect, test, type Page } from '@playwright/test'
import { signInDemo } from './demo-auth'

const dbUrl = process.env.DB_URL ?? ''
if (!dbUrl) throw new Error('DB_URL is required for read-only verification and fiscal bootstrap')
function sql(statement: string) { return execFileSync('psql', [dbUrl, '-At', '-v', 'ON_ERROR_STOP=1', '-c', statement], { encoding: 'utf8' }).trim() }
function q(value: string) { return `'${value.replaceAll("'", "''")}'` }
function validCpf(seed: string) {
  const digits = seed.replace(/\D/g, '').padEnd(9, '1').slice(0, 9).split('').map(Number)
  const check = (base: number[], factor: number) => { const sum = base.reduce((acc, digit, i) => acc + digit * (factor - i), 0); const r = (sum * 10) % 11; return r === 10 ? 0 : r }
  digits.push(check(digits, 10)); digits.push(check(digits, 11)); return digits.join('')
}
async function createFiscalPerson(page: Page, name: string, cpf: string) {
  await page.goto('/pessoas/nova', { waitUntil: 'domcontentloaded' })
  await page.getByLabel('Nome civil').fill(name); await page.getByLabel('Data de nascimento').fill('1990-01-01'); await page.getByLabel('CPF').fill(cpf)
  await page.getByLabel('Logradouro').fill('Rua Homologação'); await page.getByLabel('Número').fill('100'); await page.getByLabel('Bairro').fill('Centro'); await page.getByLabel('Cidade').fill('Divinópolis'); await page.getByLabel('UF').fill('MG'); await page.getByLabel('CEP').fill('35500000')
  await page.getByRole('button', { name: 'Cadastrar pessoa' }).click(); await expect(page).toHaveURL(/\/pessoas$/)
  await expect.poll(() => sql(`select id from public.people where civil_name=${q(name)} order by created_at desc limit 1`)).not.toBe('')
  const id = sql(`select id from public.people where civil_name=${q(name)} order by created_at desc limit 1`)
  expect(sql(`select cpf_normalized||'|'||(fiscal_address->>'city')||'|'||(fiscal_address->>'state') from public.people where id=${q(id)}`)).toBe(`${cpf}|Divinópolis|MG`)
  return id
}
async function createPastAppointmentAndCharge(page: Page, personId: string) {
  await page.goto('/agenda/gerenciar', { waitUntil: 'domcontentloaded' }); const form = page.locator('section[aria-labelledby="new-appointment-heading"] form')
  await form.locator('select[name="person_id"]').selectOption(personId); await form.locator('select[name="service_id"]').selectOption('d0200000-0000-4000-8000-000000000001'); await form.locator('input[name="starts_at_local"]').fill('2020-02-03T14:00'); await form.getByRole('button', { name: 'Criar consulta' }).click()
  await expect.poll(() => sql(`select id from public.appointments where person_id=${q(personId)} order by created_at desc limit 1`)).not.toBe(''); const id = sql(`select id from public.appointments where person_id=${q(personId)} order by created_at desc limit 1`)
  await page.goto('/agenda?view=day&date=2020-02-03', { waitUntil: 'domcontentloaded' }); const item = page.locator('li.appointment-calendar__item').filter({ has: page.locator(`input[value="${id}"]`) }); await item.getByText('Ver detalhes').click(); const status = item.getByRole('form', { name: 'Alterar status da consulta' }); await status.locator('select[name="command"]').selectOption('cancel_late'); await status.getByRole('button', { name: 'Aplicar' }).click()
  await expect.poll(() => sql(`select status from public.appointments where id=${q(id)}`)).toBe('cancelled_late'); await page.goto('/agenda?view=day&date=2020-02-03', { waitUntil: 'domcontentloaded' }); const charged = page.locator('li.appointment-calendar__item').filter({ hasText: nameFrom(personId) }); await charged.getByText('Ver detalhes').click(); await charged.getByRole('button', { name: 'Cobrar falta/cancelamento fora do prazo' }).click()
  await expect.poll(() => sql(`select id from public.receivables where source_type='appointment' and source_id=${q(id)} limit 1`)).not.toBe(''); return sql(`select id from public.receivables where source_type='appointment' and source_id=${q(id)} limit 1`)
}
function nameFrom(personId: string) { return sql(`select civil_name from public.people where id=${q(personId)}`) }
async function settleReceivable(page: Page, receivableId: string) {
  await page.goto('/financeiro/operacoes', { waitUntil: 'domcontentloaded' }); let card = page.locator('article').filter({ has: page.locator(`input[name="receivable_id"][value="${receivableId}"]`) }); const original = Number(sql(`select original_amount_cents from public.receivables where id=${q(receivableId)}`)) / 100
  const payment = card.locator('form:has(button:has-text("Registrar pagamento"))'); await payment.locator('input[name="amount"]').fill(original.toFixed(2)); await payment.locator('select[name="method"]').selectOption('pix'); await payment.getByRole('button', { name: 'Registrar pagamento' }).click(); await expect.poll(() => sql(`select status from public.receivables where id=${q(receivableId)}`)).toBe('paid')
  card = page.locator('article').filter({ has: page.locator(`input[name="receivable_id"][value="${receivableId}"]`) }); const adjustment = card.locator('form:has(button:has-text("Aplicar ajuste"))'); await adjustment.locator('input[name="amount"]').fill('10.00'); await adjustment.locator('select[name="direction"]').selectOption('discount'); await adjustment.locator('input[name="reason"]').fill('Ajuste homologação UI'); await adjustment.getByRole('button', { name: 'Aplicar ajuste' }).click(); await expect.poll(() => sql(`select status from public.receivables where id=${q(receivableId)}`)).toBe('refund_due')
  const paymentId = sql(`select id from public.payments where receivable_id=${q(receivableId)} order by paid_at desc limit 1`); const refund = page.locator('form').filter({ has: page.locator(`input[name="payment_id"][value="${paymentId}"]`) }); await refund.locator('input[name="amount"]').fill('10.00'); await refund.locator('input[name="reason"]').fill('Estorno homologação UI'); await refund.getByRole('button', { name: 'Registrar estorno' }).click(); await expect.poll(() => sql(`select status from public.receivables where id=${q(receivableId)}`)).toBe('paid')
}
async function createPayable(page: Page, token: string) {
  await page.goto('/financeiro/operacoes', { waitUntil: 'domcontentloaded' }); const vendorName = `Fornecedor UI ${token}`; const categoryName = `Categoria UI ${token}`
  const vendor = page.locator('form').filter({ has: page.getByRole('button', { name: 'Cadastrar fornecedor' }) }); await vendor.getByLabel('Nome do fornecedor').fill(vendorName); await vendor.getByRole('button', { name: 'Cadastrar fornecedor' }).click(); const vendorId = sql(`select id from public.vendors where legal_name=${q(vendorName)} order by created_at desc limit 1`)
  const category = page.locator('form').filter({ has: page.getByRole('button', { name: 'Cadastrar categoria' }) }); await category.getByLabel('Nome da categoria').fill(categoryName); await category.getByRole('button', { name: 'Cadastrar categoria' }).click(); const categoryId = sql(`select id from public.expense_categories where name=${q(categoryName)} order by created_at desc limit 1`)
  const create = page.locator('form').filter({ has: page.getByRole('button', { name: 'Criar conta' }) }); await create.locator('select[name="vendor_id"]').selectOption(vendorId); await create.locator('select[name="category_id"]').selectOption(categoryId); await create.locator('input[name="description"]').fill(`Conta UI ${token}`); await create.locator('input[name="amount"]').fill('100.00'); await create.locator('input[name="due_date"]').fill('2035-02-10'); await create.locator('input[name="competence"]').fill('2035-02-01'); await create.getByRole('button', { name: 'Criar conta' }).click(); const payableId = sql(`select id from public.payables where vendor_id=${q(vendorId)} order by created_at desc limit 1`)
  const pay = page.locator('form').filter({ has: page.locator(`input[name="payable_id"][value="${payableId}"]`) }); await pay.locator('input[name="amount"]').fill('100.00'); await pay.getByRole('button', { name: 'Registrar baixa' }).click(); await expect.poll(() => sql(`select status from public.payables where id=${q(payableId)}`)).toBe('paid')
}
async function createEventFlow(page: Page, personId: string, personName: string, token: string) {
  await page.goto('/eventos/operacoes', { waitUntil: 'domcontentloaded' }); const title = `Evento UI ${token}`; const create = page.locator('form').filter({ has: page.getByRole('button', { name: 'Criar evento' }) }); await create.locator('input[name="title"]').fill(title); await create.locator('input[name="starts_at_local"]').fill('2035-03-10T09:00'); await create.locator('input[name="ends_at_local"]').fill('2035-03-10T12:00'); await create.locator('input[name="capacity"]').fill('5'); await create.locator('input[name="price"]').fill('120.00'); await create.getByRole('button', { name: 'Criar evento' }).click(); const eventId = sql(`select id from public.events where title=${q(title)} limit 1`)
  await page.goto(`/eventos/operacoes?person_q=${encodeURIComponent(personName)}`, { waitUntil: 'domcontentloaded' }); const card = page.locator('article').filter({ hasText: title }); const reg = card.locator('form:has(button:has-text("Inscrever participante"))'); await reg.locator('select[name="person_id"]').selectOption(personId); await reg.getByRole('button', { name: 'Inscrever participante' }).click(); const registrationId = sql(`select id from public.event_registrations where event_id=${q(eventId)} and person_id=${q(personId)}`)
  const expense = card.locator('form:has(button:has-text("Registrar despesa"))'); await expense.locator('input[name="description"]').fill('Despesa homologação UI'); await expense.locator('input[name="amount"]').fill('35.00'); await expense.locator('select[name="paid"]').selectOption('yes'); await expense.getByRole('button', { name: 'Registrar despesa' }).click(); await expect.poll(() => sql(`select count(*) from public.event_expenses where event_id=${q(eventId)}`)).toBe('1')
  const update = page.locator('form').filter({ has: page.locator(`input[name="registration_id"][value="${registrationId}"]`) }); await update.locator('select[name="status"]').selectOption('confirmed'); await update.locator('select[name="attendance_status"]').selectOption('present'); await update.getByRole('button', { name: 'Atualizar inscrição' }).click(); await expect.poll(() => sql(`select attendance_status from public.event_registrations where id=${q(registrationId)}`)).toBe('present'); return registrationId
}
function ensureFiscalProfile() { let id = sql("select id from public.fiscal_profiles where active=true order by version desc limit 1"); if (id) return id; id = randomUUID(); sql(`insert into public.fiscal_profiles(id,version,issuer_kind,issuer_document,municipality_code,service_code,tax_regime,fiscal_address,effective_from,active) values(${q(id)},999,'individual','12345678901','3122306','8650002','pf','{"city":"Divinopolis"}'::jsonb,'2026-01-01',true)`); return id }
async function fiscalAndExports(page: Page, personId: string, registrationId: string) {
  const profileId = ensureFiscalProfile(); const treatmentId = sql("select id from public.fiscal_treatments where source_kind='event_registration' order by version desc limit 1")
  await page.goto('/fiscal/operacoes', { waitUntil: 'domcontentloaded' }); const form = page.locator('form').filter({ has: page.getByRole('button', { name: 'Emitir NFS-e mock' }) }); await form.locator('select[name="source_type"]').selectOption('event_registration'); await form.locator('input[name="source_id"]').fill(registrationId); await form.locator('select[name="person_id"]').selectOption(personId); await form.locator('select[name="payer_person_id"]').selectOption(personId); await form.locator('input[name="amount"]').fill('120.00'); await form.locator('select[name="profile_id"]').selectOption(profileId); await form.locator('select[name="treatment_id"]').selectOption(treatmentId); await form.locator('input[name="review_ack"]').check(); await form.getByRole('button', { name: 'Emitir NFS-e mock' }).click(); const docId = sql(`select id from public.fiscal_documents where source_id=${q(registrationId)} and provider='mock' order by created_at desc limit 1`); expect(docId).not.toBe(''); const cancel = page.locator('form').filter({ has: page.locator(`input[name="fiscal_document_id"][value="${docId}"]`) }); await cancel.locator('input[name="reason"]').fill('Cancelamento homologação UI'); await cancel.getByRole('button', { name: 'Cancelar NFS-e mock' }).click(); await expect.poll(() => sql(`select status from public.fiscal_documents where id=${q(docId)}`)).toBe('cancelled')
  await page.goto('/relatorios/baixar', { waitUntil: 'domcontentloaded' }); for (const [label, ext] of [['Baixar CSV','csv'],['Baixar XLSX','xlsx'],['Baixar PDF','pdf']] as const) { const d = page.waitForEvent('download'); await page.getByRole('button', { name: label }).click(); const download = await d; expect(download.suggestedFilename()).toMatch(new RegExp(`\\.${ext}$`)); expect(await download.path()).toBeTruthy(); await page.goto('/relatorios/baixar', { waitUntil: 'domcontentloaded' }) }
}

test('canonical operational homologation creates all business data through the UI', async ({ page }) => {
  const token = randomUUID().slice(0, 8); const name = `Homologação UI ${token}`; const cpf = validCpf(Date.now().toString())
  await signInDemo(page); const personId = await createFiscalPerson(page, name, cpf); const receivableId = await createPastAppointmentAndCharge(page, personId); await settleReceivable(page, receivableId); await createPayable(page, token); const registrationId = await createEventFlow(page, personId, name, token); await fiscalAndExports(page, personId, registrationId)
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/dashboard', { waitUntil: 'domcontentloaded' }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); await page.evaluate(() => { document.documentElement.style.zoom = '2' }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); await expect(page.locator('button, input, select, textarea, a').first()).toBeVisible()
})
