import Link from 'next/link'
import { PageHeader } from '@/shared/ui/page-header'
import { createServerSupabaseClient } from '@/platform/supabase/server'
import { cancelMockNfseAction, issueMockNfseAction } from './actions'

export const dynamic='force-dynamic'; export const revalidate=0
export default async function FiscalOperationsPage(){
 const c=await createServerSupabaseClient(); const [{data:profiles},{data:treatments},{data:people},{data:docs}]=await Promise.all([
  c.from('fiscal_profiles').select('id,version,issuer_kind,issuer_document,municipality_code,service_code,tax_regime,active').eq('active',true).order('version',{ascending:false}),
  c.from('fiscal_treatments').select('id,source_kind,version,issuance_rule,approved,enabled_for_live').order('source_kind'),
  c.from('people').select('id,civil_name,preferred_name,cpf_normalized,fiscal_address').order('civil_name'),
  c.from('fiscal_documents').select('id,source_type,source_id,amount_cents,status,provider,external_id,protocol,xml_path,pdf_path,issued_at,cancelled_at,person:people!fiscal_documents_person_id_fkey(civil_name)').order('created_at',{ascending:false}).limit(100)
 ]);
 return <><PageHeader title="Homologação fiscal" description="Fluxo sintético de NFS-e para teste. O provedor live permanece bloqueado."/><p><Link href="/fiscal">← Voltar ao fiscal</Link></p><aside role="status"><strong>Modo: MOCK/SANDBOX.</strong> Nenhuma NFS-e real é transmitida. A habilitação live continua dependente do gate contábil de produção.</aside>
 <section><h2>Readiness</h2><ul>{(profiles??[]).map(p=><li key={p.id}>Perfil v{p.version}: {p.issuer_document&&p.municipality_code&&p.service_code&&p.tax_regime?'completo':'incompleto'} ({p.issuer_kind})</li>)}</ul><ul>{(treatments??[]).map(t=><li key={t.id}>{t.source_kind}: {t.issuance_rule} · aprovado={String(t.approved)} · live={String(t.enabled_for_live)}</li>)}</ul></section>
 <section><h2>Solicitar NFS-e sintética</h2><form action={issueMockNfseAction} className="stack-form"><label>Origem <select name="source_type">{(treatments??[]).filter(t=>t.issuance_rule!=='not_issuable').map(t=><option key={t.id} value={t.source_kind}>{t.source_kind}</option>)}</select></label><label>ID da origem <input name="source_id" required pattern="[0-9a-fA-F-]{36}"/></label><label>Paciente <select name="person_id">{(people??[]).map(p=><option key={p.id} value={p.id}>{p.preferred_name||p.civil_name}</option>)}</select></label><label>Tomador/pagador <select name="payer_person_id">{(people??[]).map(p=><option key={p.id} value={p.id}>{p.preferred_name||p.civil_name} {p.cpf_normalized?'':'(CPF ausente)'}</option>)}</select></label><label>Valor <input name="amount" required/></label><label>Perfil fiscal <select name="profile_id">{(profiles??[]).map(p=><option key={p.id} value={p.id}>v{p.version} — {p.issuer_document}</option>)}</select></label><label>Tratamento <select name="treatment_id">{(treatments??[]).filter(t=>t.issuance_rule!=='not_issuable').map(t=><option key={t.id} value={t.id}>{t.source_kind} v{t.version} ({t.issuance_rule})</option>)}</select></label><label><input type="checkbox" name="review_ack" value="yes" required/> Revisei origem, tomador, valor e tratamento; emitir somente no mock/sandbox.</label><button type="submit">Emitir NFS-e mock</button></form></section>
 <section><h2>Documentos</h2>{(docs??[]).map(d=><article key={d.id} className="card"><h3>{d.person?.civil_name||'Pessoa'} — R$ {(d.amount_cents/100).toFixed(2)}</h3><p>{d.source_type} · {d.status} · provedor {d.provider}</p><p>External ID: {d.external_id||'—'} · protocolo: {d.protocol||'—'}</p><p>Artefatos privados: XML {d.xml_path?'✓':'—'} · PDF {d.pdf_path?'✓':'—'}</p>{d.provider==='mock'&&d.status==='issued'?<form action={cancelMockNfseAction} className="stack-form"><input type="hidden" name="fiscal_document_id" value={d.id}/><input type="hidden" name="idempotency_key" value={`ui-fiscal-cancel:${d.id}`}/><label>Motivo do cancelamento <input name="reason" required/></label><button type="submit">Cancelar NFS-e mock</button></form>:null}</article>)}</section></>
}
