export const APP_PERMISSIONS = [
  'patients.read',
  'patients.create',
  'patients.update',
  'patients.archive',
  'patients.relationships.manage',
  'appointments.read',
  'appointments.create',
  'appointments.update',
  'appointments.reschedule',
  'appointments.cancel',
  'appointments.confirm',
  'appointments.checkin',
  'appointments.no_show',
  'appointments.complete',
  'appointments.blocks.manage',
  'clinical.read',
  'clinical.create',
  'clinical.supersede',
  'clinical.attachments.manage',
  'clinical.documents.manage',
  'forms.read',
  'forms.send',
  'forms.manage',
  'documents.read',
  'documents.create',
  'documents.send',
  'messaging.read',
  'messaging.send',
  'messaging.templates.manage',
  'finance.read',
  'finance.receive',
  'finance.adjust',
  'finance.refund',
  'fiscal.read',
  'fiscal.issue',
  'fiscal.cancel',
  'events.read',
  'events.manage',
  'reports.operational.read',
  'reports.financial.read',
  'reports.fiscal.read',
  'users.read',
  'users.manage',
  'permissions.manage',
  'settings.manage',
  'audit.read',
  'tasks.read',
  'tasks.create',
  'tasks.update',
  'tasks.assign',
] as const

export type AppPermission = (typeof APP_PERMISSIONS)[number]
export type PermissionArea = AppPermission extends `${infer Area}.${string}` ? Area : never

export const isAppPermission = (value: string): value is AppPermission =>
  APP_PERMISSIONS.includes(value as AppPermission)
