export { APP_ROLES, isAppRole } from './domain/role'
export type { AppRole } from './domain/role'
export { authorizeStaffSession, AuthorizationError, requireRole } from './application/require-role'
export type { StaffSession } from './application/require-role'
export { getStaffSession } from './application/get-session'
